### ISSUE TITLE
dotenv (.env) file location

### ISSUE THREAD

**Issue by jayjacksonworks** [levibostian/dotenv-android#24]
Is there a way to specify the location of the .env file? Might be helpful for react-native projects where the .env file is typically in the parent directory.

**Comment by levibostian** [comment]
Hey there, @jayjacksonworks! 

At this time, no, there is not a way to specify the location of the `.env` file. That is because this gradle plugin was created and tested on native Android apps where the `.env` would always be in the root directory of the gradle project. 

Mind giving me an example of how react-native projects are setup? 

For native Android, the project file structure is like this:
```
.env 
build.gradle          <--- root level build.gradle file
app/
    - build.gradle  <---- module level build.gradle file
```

How is the file structure of react-native projects?

**Comment by jayjacksonworks** [comment]
Yep, I figured and no problem. I was able to get things working. But yes, you're right on the typical react-native project structure where all the android specific build files are in an `android` folder. For example, https://github.com/taskrabbit/ReactNativeSampleApp 

.env
/android
/ios 
/app

**Comment by levibostian** [comment]
I imagine that you could put the `.env` file in `android/` and it all should work. 

The gradle plugin looks for the `.env` file in [the root directory of the gradle project](https://github.com/levibostian/dotenv-android/blob/bf0aa1c4d0189ad83c463b25bf4cd04d97a8f854/src/main/kotlin/earth/levi/dotenv/DotEnvPlugin.kt#L116) which is probably where the top level `build.gradle` file is. In your case, the `android/` directory. 

I can see how doing this would be annoying because you might want to share a `.env` with `ios/` as well.

**Comment by jayjacksonworks** [comment]
Yep, for now I’ll just copy .env -> android/.env. But if anything changes let me know, thanks for the library!
